services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: honganh-eyeshop
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # - MONGODB_URI=mongodb://mongo:27017/mydb
    env_file:
      - .env.production
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  cron:
    build:
      context: ./cron
      dockerfile: Dockerfile.cron
    environment:
      - BASE_URL=http://app:3000
    env_file:
      - .env.production
    depends_on:
      - app

volumes:
  mongo-data:
