load_module modules/ngx_http_brotli_filter_module.so;
load_module modules/ngx_http_brotli_static_module.so;

events {}

http {
  include       mime.types;
  default_type  application/octet-stream;

  # Map để giữ hoặc xoá Accept-Encoding
  map $http_rsc $disable_encoding {
    "1" $http_accept_encoding;  # Nếu là RSC → giữ nguyên Accept-Encoding
    default "";                 # Ngược lại → xoá header -> nextjs ko nén → Nginx sẽ nén
  }

  # Gzip config
  gzip on;
  gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;

  # Brotli config
  brotli on;
  brotli_static on;
  brotli_comp_level 6;
  brotli_types text/plain text/css application/javascript application/json image/svg+xml application/xml+rss text/html;

  server {
    listen 80;
    server_name localhost;

    location / {
      proxy_pass http://app:3000;
      proxy_http_version 1.1;

      # Áp dụng map đã cấu hình
      proxy_set_header Accept-Encoding $disable_encoding;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}

